import './globals.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/inject-style';
export const metadata = {
  title: 'eBay Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
